stages:
  - test
  - secret-detection

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  stage: test

secret_detection:
  stage: secret-detection
