---
apiVersion: v1
kind: Secret
metadata:
  name: vulcano-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  service-admin-password: {{ .Values.auth.serviceAdminPassword | default "" | b64enc | quote }}
---
{{- if and (not .Values.mongodb.enabled) .Values.mongodb.externalHost (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
---
{{- end }}
{{- if and (or .Values.rabbitmq.enabled .Values.rabbitmq.externalHost) (not .Values.rabbitmq.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | default (printf "%s-erlang" .Release.Name | sha256sum | trunc 32) | b64enc | quote }}
---
{{- end }}
{{- if .Values.imagePullSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-io
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "vulcano.dockerconfigjson" . | b64enc | quote }}
---
{{- end }}
{{- if not .Values.integrations.helmut.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: helmut-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  helmut-client-secret: {{ coalesce .Values.integrations.helmut.clientSecret .Values.helmut.clientSecret | default "" | b64enc | quote }}
---
{{- end }}
{{- if not .Values.integrations.ndr.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ndr-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  ndr-vdb-password: {{ .Values.integrations.ndr.vdbPassword | default "" | b64enc | quote }}
---
{{- end }}
{{- if and .Values.integrations.octopus.enabled (not .Values.integrations.octopus.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: octopus-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  octopus-password: {{ coalesce .Values.integrations.octopus.password .Values.octopus.password | default "" | b64enc | quote }}
---
{{- end }}
{{- if not .Values.integrations.vidispine.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vidispine-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  vidispine-client-secret: {{ coalesce .Values.integrations.vidispine.clientSecret .Values.vidispine.clientSecret | default "" | b64enc | quote }}
---
{{- end }}
{{- if and (eq .Values.auth.mode "KEYCLOAK") (not .Values.auth.keycloak.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-client-secret: {{ .Values.auth.keycloak.clientSecret | default "" | b64enc | quote }}
---
{{- end }}
