---
{{- if and .Values.mongodb.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mongodb.auth.rootUser | b64enc | quote }}
  password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
---
{{- end }}
{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc | quote }}
---
{{- end }}
{{- if .Values.imagePullSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-io
  namespace: {{ include "vulcano.namespace" . }}
  labels:
    {{- include "vulcano.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "vulcano.dockerconfigjson" . | b64enc | quote }}
---
{{- end }}
